script: 'bundle exec rake'
language: ruby
os:
  - linux
  - osx
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - rbx-2
  - ruby-head
  - jruby-9.0.0.0
  - jruby-head
addons:
  artifacts:
    debug: true
    paths:
      - lib/bel/libbel.so
      - lib/bel/libbel.bundle
matrix:
  allow_failures:
    - os: osx
