language: ruby
sudo: false
env:
  - BR_ISOLATE="yes" BR_GEM_INSTALL_OPTS="--no-user-install"
install: scripts/gem-install-devdeps.sh
script: scripts/ci.sh
os:
  - linux
  - osx
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - jruby-9.0.5.0
  - rbx-2
  - rbx-3
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - os: osx
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3 # Seems to be trouble installing 3.14 on Travis CI.

