language: ruby
sudo: false
env:
  - BR_ISOLATE="yes" BR_GEM_INSTALL_OPTS="--no-user-install --no-lock"
install: scripts/gem-install-devdeps.sh
script: scripts/ci.sh
os:
  - linux
  - osx
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - rbx-2
  - ruby-head
  - jruby-9.0.4.0
  - jruby-head
addons:
  artifacts:
    debug: true
    paths:
      - lib/bel/libbel.so
      - lib/bel/libbel.bundle
matrix:
  allow_failures:
    - os: osx
    - rvm: ruby-head
    - rvm: jruby-head

