#!/usr/bin/env python3
'''
Copyright (c) 2011-2014 Nick Bargnesi <nick@den-4.com>

Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
files (the "Software"), to deal in the Software without
restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following
conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

@author: Nick Bargnesi
'''

import os
import sys


def exit_failure():
    '''Exits with status 1.'''
    sys.exit(1)


def exit_success():
    '''Exits with status 0.'''
    sys.exit(0)


def install_or_die(library):
    '''Install the library through pip or die trying.'''
    try:
        import pip
    except ImportError as ie:
        print("You're missing pip (%s)." % ie)
        exit_failure()
    rslt = pip.main(['install', '--user', library])
    if rslt != 0:
        exit_failure()
    print('Installed %s... ready to try again.' % (library))
    exit_failure()


def usage():
    '''
    Prints usage information to stdout.
    '''
    print('Usage:', ME, '<DIR>...')
    print("Try '" + ME, " --help' for more information.")

    
def help():
    '''
    Prints usage and help information to stdout.
    '''
    print('Usage:', ME, '<DIR>...')
    print('Waits until a file is written in any of the directories provided')
    print('as arguments. This program will exit with a return code of 0 unless')
    print('it is interrupted.')
    print()
    print('If no directories are provided, all directories under the current')
    print('working directory will be used.')
    print()
    print('Example:', ME, '$HOME')
    print()
    print('Miscellaneous:')
    print('  -h, --help\t\tdisplay this help and exit')
    print()
    print('gate home page: <https://github.com/nbargnesi/scripts>')
    

from os.path import isdir
from os import getcwd
from threading import Event
try:
    from watchdog.observers import Observer
except ImportError as ie:
    print("You're missing watchdog (%s)." % ie)
    reply = input('Try to install it? (y/n): ')
    if reply == 'y':
        install_or_die('watchdog')
    else:
        exit_failure()
    from watchdog.observers import Observer

ev = Event()

class Handler:
    '''Handles filesystem events.'''
    def dispatch(self, event):
        path = event.src_path
        evtype = event.event_type
        print('%s %s' % (path, evtype))
        ev.set()


if __name__ == '__main__':
    ME = sys.argv[0]
    
    for arg in sys.argv[1:]:
        if arg == '--help' or arg == '-h':
            help()
            exit_failure()        

    DIRS = list()
    if len(sys.argv) > 1:
        DIRS = sys.argv[1:]
        SUCCESS = True
        for d in DIRS:
            if not isdir(d):
                print('%s: not a directory' % d)
                SUCCESS = False
        if not SUCCESS:
            exit_failure()
         
    global observer
    observer = Observer()
    handler = Handler()
    if not DIRS:
        # all directories under the current will be used 
        observer.schedule(handler, getcwd(), recursive=True)
    else:
        for d in DIRS:
            observer.schedule(handler, d)

    observer.start()
    try:
        ev.wait()
    except KeyboardInterrupt as ki:
        observer.stop()
        exit_failure()
    observer.stop()
    exit_success()

